### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by stevenosloan** [comment]
I'm not against it -- just feels like it may overlap codeclimate a bit. I'm curious what advantages it would provide as I think I'd rather pick one or the other.

**Comment by korzonek** [comment]
@stevenosloan there are a few things that are not available in code climate and you can find in codebeat.

* _Multi-Language support for mobile and web applications_. We implemented all algorithms on our own. It means relatively quickly we can support more languages both for mobile and web. At this stage we analyse **Swift, Ruby, Python** and **Go**.
* _Quick Wins_. After analysing your project we will suggest you issues in code with the biggest overall impact on your project's health. Try to refactor these hot spots first and see how your GPA improves.
* _Compare Changes_. In the stream of Recent Changes you will be able see what exactly caused your classes to improve or degrade.

We are also about to release nice support for pull requests in codebeat.

**Comment by kenliu** [comment]
code beat and code climate are direct competitors

**Comment by siegy22** [comment]
@stevenosloan I think this PR can be closed, as you're using codeclimate and that's fine :smile:

**Pull request closed without merging**
