### PR TITLE
Fix incorrect matching for links with parentheses

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by stevenosloan** [comment]
Thanks for pointing this out! Fixes should be out now in 2.3.2

**Comment by revolter** [comment]
Shouldn't houndci's warning be solved?

**Comment by siegy22** [comment]
@revolter It's still the maintainer who says what's okay and what's not.
I guess @stevenosloan uses 80 as a soft limit and 120 to 125 for the hard limit 😄

**Comment by revolter** [comment]
@siegy22, Of course, that's why I asked.

**Pull request merged**
