### PR TITLE
add option[:at] to #ping

### PR DESCRIPTION
**Pull request by kazuooooo**
Hi, I added at option to #ping method.

In default text option, need to write like this to add @ or special command.

```ruby
notifier.ping "<@john> <@ken> <@smith> <!here> <@tailar> Hi let's go drink tonight!"
```
message tend to be long and little hard to read

so I added at option it can be written like this.

```ruby
notifier.ping "Hi let's go drink tonight!", at: [:john, :ken, :smith, :here, :tailer]
# => {text: "<@john> <@ken> <@smith> <!here> <@tailar> Hi let's go drink tonight!"}
```

thanks,

### CODE REVIEW

**Comment by kazuooooo** [comment]
sorry, I don't know well why travis fails...

**Comment by kazuooooo** [comment]
@stevenosloan 
Thank you for your review.
OK, I'm going to try moving it to middleware.

**Comment by kazuooooo** [comment]
@stevenosloan 
hi :smile: I moved at option to middle ware.
could you check again?

```ruby
notifier = Slack::Notifier.new
# it can be set as option
# notifier = Slack::Notifier.new url do
#   middleware :at [:default_at_user]
# end
notifier.ping("Hi let's go drink tonight!", at: [:john, :ken, :smith, :here, :tailer])
# => {text: "<@john> <@ken> <@smith> <!here> <@tailar> Hi let's go drink tonight!"}
```

**Comment by kazuooooo** [comment]
I don't still know why travis fails....
Probably, it's not caused of my implementation.
Sorry for that 🤕

**Comment by stevenosloan** [comment]
Yeah, no worries about those failures -- were coming from https://github.com/sickill/rainbow/issues/48 (hoping the suggested fix works).

Thanks for taking the time to reformat that! I'll look at cutting a `2.1.0` release sometime this week.

**Comment by kazuooooo** [comment]
Thank you so much :) !!
Looking forward next release!!

**Pull request merged**
